### ISSUE TITLE
Can not install through Composer

### ISSUE THREAD

**Issue by welcoMattic** [Vinelab/laravel-editor#1]
I catch this error when I execute `composer update`:

``` log
The requested package vinelab/laravel-editor could not be found in any version, there may be a typo in the package name.
```

EDIT: it works with 

``` json
"vinelab/laravel-editor": "dev-master"
```

But, I can't install it on Laravel 5.0.2.

Is it planned to make a L5 version of your package ?

**Comment by Mulkave** [comment]
Closed in ac5b63c6b467e59bc5111900c61d985f19eb85e1
